-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_INS INS
    INNER JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.SEX_UPON_OUTCOME  NOT LIKE 'Intact%' 
    AND INS.SEX_UPON_INTAKE LIKE 'Intact%'
    
    
