-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.NAME #, DATEDIFF(AO.DATETIME, AI.DATETIME), AI.DATETIME AS IN1, AO.DATETIME AS OUT1
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC
LIMIT 2