SELECT ID, 
    CASE
     WHEN (RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / COUNT(ID) OVER()) <= 0.25 THEN 'CRITICAL'
     WHEN (RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / COUNT(ID) OVER()) <= 0.50 THEN 'HIGH'
     WHEN (RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / COUNT(ID) OVER()) <= 0.75 THEN 'MEDIUM'
     ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID
