-- 코드를 입력하세요
SELECT UU.USER_ID, UU.NICKNAME, 
    CONCAT(UU.CITY, " ", UU.STREET_ADDRESS1, " ", UU.STREET_ADDRESS2) AS 전체주소, 
    CONCAT(SUBSTRING(UU.TLNO, 1, 3), '-', 
           SUBSTRING(UU.TLNO, 4, 4), '-', 
           SUBSTRING(UU.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER UU
JOIN (
    SELECT WRITER_ID, COUNT(*) AS COUNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) UB
ON UB.WRITER_ID = UU.USER_ID
WHERE UB.COUNT >= 3
ORDER BY UU.USER_ID DESC