SELECT FI.FISH_COUNT, FN.FISH_NAME
FROM
(
    SELECT COUNT(ID) AS FISH_COUNT, FISH_TYPE
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
) FI
LEFT JOIN FISH_NAME_INFO FN
ON FI.FISH_TYPE = FN.FISH_TYPE
ORDER BY FI.FISH_COUNT DESC;
