-- 코드를 작성해주세요

WITH RECURSIVE cte AS (

    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL
    
    SELECT CH.ID, CH.PARENT_ID, PA.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA CH
    INNER JOIN cte AS PA
    ON CH.PARENT_ID = PA.ID
)

SELECT COUNT(C.ID) AS COUNT, C.GENERATION
FROM cte C
LEFT JOIN ECOLI_DATA E
ON C.ID = E.PARENT_ID
WHERE E.PARENT_ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION


