-- 코드를 작성해주세요
SELECT ED1.ID, ED1.GENOTYPE, ED2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED1
JOIN ECOLI_DATA ED2
ON ED1.PARENT_ID = ED2.ID

WHERE ED2.GENOTYPE & ED1.GENOTYPE = ED2.GENOTYPE

ORDER BY ED1.ID