-- 코드를 입력하세요
SELECT MONTH(T.START_DATE) AS MONTH, T.CAR_ID, COUNT(T.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T
JOIN (
    SELECT CAR_ID, COUNT(CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE >= '2022-08-01' AND 
        START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING RECORDS >= 5
) J
ON T.CAR_ID = J.CAR_ID
WHERE 
        START_DATE >= '2022-08-01' AND 
        START_DATE < '2022-11-01'
GROUP BY T.CAR_ID, MONTH(T.START_DATE)
# HAVING COUNT(T.CAR_ID) > 0
ORDER BY MONTH ASC, T.CAR_ID DESC