-- 코드를 작성해주세요

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
JOIN (
    SELECT SUM(CODE) AS CODE_SUM
    FROM SKILLCODES
    WHERE NAME = "C#" OR NAME = "Python"
) S
ON (D.SKILL_CODE & S.CODE_SUM) > 0
ORDER BY ID ASC