-- 코드를 입력하세요
SELECT P.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR P
JOIN (
    SELECT CAR_ID, MONTH(START_DATE)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE MONTH(START_DATE) = 10
    GROUP BY CAR_ID
) J
ON P.CAR_ID = J.CAR_ID
WHERE P.CAR_TYPE = '세단'
ORDER BY P.CAR_ID DESC