WITH RankedFish AS (
    SELECT 
        ID, 
        FISH_TYPE, 
        LENGTH,
        ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS rnk
    FROM FISH_INFO
)
SELECT J.ID, T.FISH_NAME, J.LENGTH
FROM FISH_NAME_INFO T
JOIN (
    SELECT ID, FISH_TYPE, LENGTH
    FROM RankedFish
    WHERE rnk = 1
) J
ON T.FISH_TYPE = J.FISH_TYPE
ORDER BY J.ID
