-- 코드를 작성해주세요
SELECT SC.SCORE, HE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE
JOIN
    (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE 
        GROUP BY EMP_NO, YEAR
        ORDER BY SCORE DESC
        LIMIT 1
    ) AS SC
ON HE.EMP_NO = SC.EMP_NO
    