-- 코드를 입력하세요
SELECT TITLE, B1.BOARD_ID, B2.REPLY_ID, B2.WRITER_ID, B2.CONTENTS, DATE_FORMAT(B2.CREATED_DATE,"%Y-%m-%d")
FROM USED_GOODS_BOARD B1
JOIN USED_GOODS_REPLY B2
ON B1.BOARD_ID = B2.BOARD_ID
WHERE YEAR(B2.CREATED_DATE) = 2022 AND MONTH(B1.CREATED_DATE) = 10
ORDER BY b2.CREATED_DATE ASC, TITLE ASC