-- 코드를 입력하세요
SELECT
    CONCAT("/home/grep/src/", UB.BOARD_ID, "/", UF.FILE_ID, UF.FILE_NAME, UF.FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) UB
JOIN USED_GOODS_FILE UF
ON UB.BOARD_ID = UF.BOARD_ID
ORDER BY UF.FILE_ID DESC