-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(J.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) J
ON B.BOOK_ID = J.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY